package com.study.springboot.mapper;

import com.study.springboot.domain.CountryLanguage;
import com.study.springboot.domain.CountryLanguageKey;

public interface CountryLanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Sun Jan 28 16:13:24 CST 2018
     */
    int deleteByPrimaryKey(CountryLanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Sun Jan 28 16:13:24 CST 2018
     */
    int insert(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Sun Jan 28 16:13:24 CST 2018
     */
    int insertSelective(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Sun Jan 28 16:13:24 CST 2018
     */
    CountryLanguage selectByPrimaryKey(CountryLanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Sun Jan 28 16:13:24 CST 2018
     */
    int updateByPrimaryKeySelective(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Sun Jan 28 16:13:24 CST 2018
     */
    int updateByPrimaryKey(CountryLanguage record);
}